# Generated by Django 2.1 on 2018-09-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180903_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='veiculo',
            field=models.ForeignKey(on_delete='', to='core.Veiculo'),
        ),
    ]
