# Generated by Django 2.1 on 2018-09-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180905_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='veiculo',
            field=models.ForeignKey(on_delete=False, to='core.Veiculo'),
        ),
    ]
